"""separar ejecuciones y resultados de prediccion

Revision ID: 0ed3d7602801
Revises: a522f27d7f8e
Create Date: 2026-09-02 01:07:17.297723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed3d7602801'
down_revision: Union[str, Sequence[str], None] = 'a522f27d7f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id', 'prediction_date', name='uq_prediction_results_prediction_date')
    )
    op.create_index(op.f('ix_prediction_results_prediction_date'), 'prediction_results', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_prediction_results_prediction_id'), 'prediction_results', ['prediction_id'], unique=False)
    op.add_column('predictions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('predictions', sa.Column('model_version_id', sa.Integer(), nullable=True))
    op.add_column('predictions', sa.Column('business_series_id', sa.Integer(), nullable=True))
    op.add_column('predictions', sa.Column('horizon', sa.Integer(), nullable=False))
    op.add_column('predictions', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('predictions', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('predictions', sa.Column('status', sa.String(length=30), nullable=False))
    op.add_column('predictions', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_predictions_business_series_id'), 'predictions', ['business_series_id'], unique=False)
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_dataset_id'), 'predictions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_predictions_end_date'), 'predictions', ['end_date'], unique=False)
    op.create_index(op.f('ix_predictions_model_id'), 'predictions', ['model_id'], unique=False)
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_predictions_start_date'), 'predictions', ['start_date'], unique=False)
    op.create_index(op.f('ix_predictions_status'), 'predictions', ['status'], unique=False)
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    op.drop_constraint(op.f('predictions_dataset_id_fkey'), 'predictions', type_='foreignkey')
    op.drop_constraint(op.f('predictions_model_id_fkey'), 'predictions', type_='foreignkey')
    op.create_foreign_key(None, 'predictions', 'business_series', ['business_series_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'predictions', 'model_versions', ['model_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'predictions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'predictions', 'datasets', ['dataset_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'predictions', 'models', ['model_id'], ['id'], ondelete='CASCADE')
    op.drop_column('predictions', 'predicted_value')
    op.drop_column('predictions', 'prediction_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('prediction_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('predictions', sa.Column('predicted_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.create_foreign_key(op.f('predictions_model_id_fkey'), 'predictions', 'models', ['model_id'], ['id'])
    op.create_foreign_key(op.f('predictions_dataset_id_fkey'), 'predictions', 'datasets', ['dataset_id'], ['id'])
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_status'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_start_date'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_end_date'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_dataset_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_business_series_id'), table_name='predictions')
    op.drop_column('predictions', 'completed_at')
    op.drop_column('predictions', 'status')
    op.drop_column('predictions', 'end_date')
    op.drop_column('predictions', 'start_date')
    op.drop_column('predictions', 'horizon')
    op.drop_column('predictions', 'business_series_id')
    op.drop_column('predictions', 'model_version_id')
    op.drop_column('predictions', 'user_id')
    op.drop_index(op.f('ix_prediction_results_prediction_id'), table_name='prediction_results')
    op.drop_index(op.f('ix_prediction_results_prediction_date'), table_name='prediction_results')
    op.drop_table('prediction_results')
    # ### end Alembic commands ###
