"""adaptar reportes y exportaciones a storage

Revision ID: 1737035df1fb
Revises: 6ac688ffd81d
Create Date: 2026-09-02 00:18:40.487236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1737035df1fb'
down_revision: Union[str, Sequence[str], None] = '6ac688ffd81d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exports', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('exports', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('exports', sa.Column('export_format', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_exports_created_at'), 'exports', ['created_at'], unique=False)
    op.create_index(op.f('ix_exports_export_format'), 'exports', ['export_format'], unique=False)
    op.create_index(op.f('ix_exports_status'), 'exports', ['status'], unique=False)
    op.create_index(op.f('ix_exports_user_id'), 'exports', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'exports', ['storage_path'])
    op.create_foreign_key(None, 'exports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exports', 'format')
    op.add_column('reports', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('reports', sa.Column('filename', sa.String(length=255), nullable=False))
    op.add_column('reports', sa.Column('report_format', sa.String(length=30), nullable=False))
    op.add_column('reports', sa.Column('status', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_report_format'), 'reports', ['report_format'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'reports', ['storage_path'])
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reports', 'name')
    op.drop_column('reports', 'format')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('format', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='unique')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_format'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_column('reports', 'status')
    op.drop_column('reports', 'report_format')
    op.drop_column('reports', 'filename')
    op.drop_column('reports', 'user_id')
    op.add_column('exports', sa.Column('format', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.drop_constraint(None, 'exports', type_='unique')
    op.drop_index(op.f('ix_exports_user_id'), table_name='exports')
    op.drop_index(op.f('ix_exports_status'), table_name='exports')
    op.drop_index(op.f('ix_exports_export_format'), table_name='exports')
    op.drop_index(op.f('ix_exports_created_at'), table_name='exports')
    op.drop_column('exports', 'export_format')
    op.drop_column('exports', 'filename')
    op.drop_column('exports', 'user_id')
    # ### end Alembic commands ###
