"""agregar trazabilidad de procesamiento de datasets

Revision ID: a522f27d7f8e
Revises: b68921aa1eed
Create Date: 2026-09-02 00:40:48.686639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a522f27d7f8e'
down_revision: Union[str, Sequence[str], None] = 'b68921aa1eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('parent_dataset_id', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('processing_stage', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_datasets_parent_dataset_id'), 'datasets', ['parent_dataset_id'], unique=False)
    op.create_index(op.f('ix_datasets_processing_stage'), 'datasets', ['processing_stage'], unique=False)
    op.create_foreign_key(None, 'datasets', 'datasets', ['parent_dataset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_index(op.f('ix_datasets_processing_stage'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_parent_dataset_id'), table_name='datasets')
    op.drop_column('datasets', 'processing_stage')
    op.drop_column('datasets', 'parent_dataset_id')
    # ### end Alembic commands ###
