"""relacionar modelos con series de negocio

Revision ID: a852299ef747
Revises: 0ef574d102cf
Create Date: 2026-09-02 01:22:21.387364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a852299ef747'
down_revision: Union[str, Sequence[str], None] = '0ef574d102cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('business_series_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_models_active'), 'models', ['active'], unique=False)
    op.create_index(op.f('ix_models_business_series_id'), 'models', ['business_series_id'], unique=False)
    op.create_index(op.f('ix_models_model_type'), 'models', ['model_type'], unique=False)
    op.create_foreign_key(None, 'models', 'business_series', ['business_series_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_index(op.f('ix_models_model_type'), table_name='models')
    op.drop_index(op.f('ix_models_business_series_id'), table_name='models')
    op.drop_index(op.f('ix_models_active'), table_name='models')
    op.drop_column('models', 'business_series_id')
    # ### end Alembic commands ###
