"""crear tablas anomalies e inventory observations

Revision ID: bb6f84d15c08
Revises: 59917724bd1b
Create Date: 2026-09-02 21:24:17.207846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6f84d15c08'
down_revision: Union[str, Sequence[str], None] = '59917724bd1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_series_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('opening_stock', sa.Float(), nullable=False),
    sa.Column('replenishment_quantity', sa.Float(), nullable=False),
    sa.Column('actual_demand', sa.Float(), nullable=False),
    sa.Column('closing_stock', sa.Float(), nullable=False),
    sa.Column('predicted_demand', sa.Float(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_series_id'], ['business_series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_series_id', 'observation_date', 'phase', name='uq_inventory_observation_series_date_phase')
    )
    op.create_index(op.f('ix_inventory_observations_business_series_id'), 'inventory_observations', ['business_series_id'], unique=False)
    op.create_index(op.f('ix_inventory_observations_created_at'), 'inventory_observations', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_observations_observation_date'), 'inventory_observations', ['observation_date'], unique=False)
    op.create_index(op.f('ix_inventory_observations_phase'), 'inventory_observations', ['phase'], unique=False)
    op.create_index(op.f('ix_inventory_observations_source_type'), 'inventory_observations', ['source_type'], unique=False)
    op.create_index(op.f('ix_inventory_observations_user_id'), 'inventory_observations', ['user_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_series_id', sa.Integer(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('prediction_result_id', sa.Integer(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_series_id'], ['business_series.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_result_id'], ['prediction_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_result_id', 'anomaly_type', 'method', name='uq_anomalies_prediction_result_type_method')
    )
    op.create_index(op.f('ix_anomalies_anomaly_type'), 'anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_anomalies_business_series_id'), 'anomalies', ['business_series_id'], unique=False)
    op.create_index(op.f('ix_anomalies_detected_at'), 'anomalies', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomalies_method'), 'anomalies', ['method'], unique=False)
    op.create_index(op.f('ix_anomalies_model_id'), 'anomalies', ['model_id'], unique=False)
    op.create_index(op.f('ix_anomalies_prediction_id'), 'anomalies', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_anomalies_prediction_result_id'), 'anomalies', ['prediction_result_id'], unique=False)
    op.create_index(op.f('ix_anomalies_severity'), 'anomalies', ['severity'], unique=False)
    op.create_index(op.f('ix_anomalies_status'), 'anomalies', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anomalies_status'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_severity'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_prediction_result_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_prediction_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_model_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_method'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_detected_at'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_business_series_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_anomaly_type'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index(op.f('ix_inventory_observations_user_id'), table_name='inventory_observations')
    op.drop_index(op.f('ix_inventory_observations_source_type'), table_name='inventory_observations')
    op.drop_index(op.f('ix_inventory_observations_phase'), table_name='inventory_observations')
    op.drop_index(op.f('ix_inventory_observations_observation_date'), table_name='inventory_observations')
    op.drop_index(op.f('ix_inventory_observations_created_at'), table_name='inventory_observations')
    op.drop_index(op.f('ix_inventory_observations_business_series_id'), table_name='inventory_observations')
    op.drop_table('inventory_observations')
    # ### end Alembic commands ###
