"""crear estructura inicial del sistema

Revision ID: c5272b11ebd2
Revises: 
Create Date: 2026-09-01 10:56:24.256498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5272b11ebd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_entity_id', sa.String(length=150), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_series_external_entity_id'), 'business_series', ['external_entity_id'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('file_format', sa.String(length=30), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_variables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variable_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_variables_name'), 'external_variables', ['name'], unique=True)
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('dataset_external_variables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('external_variable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['external_variable_id'], ['external_variables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_external_variables_dataset_id'), 'dataset_external_variables', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_external_variables_external_variable_id'), 'dataset_external_variables', ['external_variable_id'], unique=False)
    op.create_table('external_variable_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('variable_id', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.String(length=255), nullable=True),
    sa.Column('business_key', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['variable_id'], ['external_variables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_variable_values_business_key'), 'external_variable_values', ['business_key'], unique=False)
    op.create_index(op.f('ix_external_variable_values_reference_date'), 'external_variable_values', ['reference_date'], unique=False)
    op.create_index(op.f('ix_external_variable_values_variable_id'), 'external_variable_values', ['variable_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('feature_config', sa.JSON(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_is_active'), 'model_versions', ['is_active'], unique=False)
    op.create_index(op.f('ix_model_versions_model_id'), 'model_versions', ['model_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_role', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('requires_action', sa.Boolean(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_category'), 'notifications', ['category'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_entity_id'), 'notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_entity_type'), 'notifications', ['entity_type'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_role'), 'notifications', ['recipient_role'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('prediction_date', sa.Date(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retraining_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retraining_policies_model_id'), 'retraining_policies', ['model_id'], unique=False)
    op.create_table('trainings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_uuid', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_uuid'), 'user_sessions', ['session_uuid'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('model_deployments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=30), nullable=False),
    sa.Column('deployment_status', sa.String(length=30), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_deployments_model_version_id'), 'model_deployments', ['model_version_id'], unique=False)
    op.create_table('model_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_type', sa.String(length=50), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('mse', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('smape', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('training_time_seconds', sa.Float(), nullable=True),
    sa.Column('prediction_time_seconds', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('ranking_position', sa.Integer(), nullable=True),
    sa.Column('is_best_model', sa.Boolean(), nullable=False),
    sa.Column('evaluation_config', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_evaluations_dataset_id'), 'model_evaluations', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_model_evaluations_evaluated_at'), 'model_evaluations', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_model_evaluations_evaluation_type'), 'model_evaluations', ['evaluation_type'], unique=False)
    op.create_index(op.f('ix_model_evaluations_is_best_model'), 'model_evaluations', ['is_best_model'], unique=False)
    op.create_index(op.f('ix_model_evaluations_model_id'), 'model_evaluations', ['model_id'], unique=False)
    op.create_index(op.f('ix_model_evaluations_model_version_id'), 'model_evaluations', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_model_evaluations_training_id'), 'model_evaluations', ['training_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=100), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_revoked'), 'refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('retraining_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.Integer(), nullable=True),
    sa.Column('new_version_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['new_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retraining_runs_model_id'), 'retraining_runs', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retraining_runs_model_id'), table_name='retraining_runs')
    op.drop_table('retraining_runs')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_model_evaluations_training_id'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_model_version_id'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_model_id'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_is_best_model'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_evaluation_type'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_evaluated_at'), table_name='model_evaluations')
    op.drop_index(op.f('ix_model_evaluations_dataset_id'), table_name='model_evaluations')
    op.drop_table('model_evaluations')
    op.drop_index(op.f('ix_model_deployments_model_version_id'), table_name='model_deployments')
    op.drop_table('model_deployments')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_uuid'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('trainings')
    op.drop_index(op.f('ix_retraining_policies_model_id'), table_name='retraining_policies')
    op.drop_table('retraining_policies')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_role'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_category'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_model_versions_model_id'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_is_active'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_external_variable_values_variable_id'), table_name='external_variable_values')
    op.drop_index(op.f('ix_external_variable_values_reference_date'), table_name='external_variable_values')
    op.drop_index(op.f('ix_external_variable_values_business_key'), table_name='external_variable_values')
    op.drop_table('external_variable_values')
    op.drop_index(op.f('ix_dataset_external_variables_external_variable_id'), table_name='dataset_external_variables')
    op.drop_index(op.f('ix_dataset_external_variables_dataset_id'), table_name='dataset_external_variables')
    op.drop_table('dataset_external_variables')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reports')
    op.drop_table('models')
    op.drop_index(op.f('ix_external_variables_name'), table_name='external_variables')
    op.drop_table('external_variables')
    op.drop_table('exports')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_business_series_external_entity_id'), table_name='business_series')
    op.drop_table('business_series')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
